name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: shallow checkout
        uses: actions/checkout@v2
        with:
            fetch-depth: 0 # Required to retrieve git history for Chromatic
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-    
      - name: Install deps 
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Lint
        run: npm run lint
      - name: Types
        run: npm run types
      - name: Chromatic
        run: npm run chromatic -- --exit-zero-on-changes
      - name: Test
        run: npm run test -- --coverage
      - name: Post coverage
        run: bash <(curl -s https://codecov.io/bash) -f ./coverage/coverage-final.json